### ISSUE TITLE
Exception when DataMember specifies the name different from the property name. 

### ISSUE THREAD

**Issue by dmitry-pavlov** [mattfrear/Swashbuckle.AspNetCore.Examples#25]
If you have property in your model class marked like this:
```
[DataMember(Name="first")
public string FirstName { get; set; }
```

You will get the exception: 
```
System.Collections.Generic.KeyNotFoundException occurred
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Swashbuckle.AspNetCore.Examples.DescriptionOperationFilter.SetResponseModelDescriptions(Operation operation, ISchemaRegistry schemaRegistry, ApiDescription apiDescription) in D:\Work\GitHub\Swashbuckle.AspNetCore.Examples\src\Swashbuckle.AspNetCore.Examples\DescriptionOperationFilter.cs:line 49
   at Swashbuckle.AspNetCore.Examples.DescriptionOperationFilter.Apply(Operation operation, OperationFilterContext context) in D:\Work\GitHub\Swashbuckle.AspNetCore.Examples\src\Swashbuckle.AspNetCore.Examples\DescriptionOperationFilter.cs:line 19
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()

```

**Comment by dmitry-pavlov** [comment]
I have created a PR which contains the fix for this bug here https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/pull/24 

Please consider to merge to the master branch.

**Comment by mattfrear** [comment]
Fixed with merge, thanks. Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.4.2
